// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zendckctfeyfkdcmjrcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbmRja2N0ZmV5ZmtkY21qcmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODIyNTIsImV4cCI6MjA2MTY1ODI1Mn0.BimXYQLANigANnBDFwj5jtQMEYY6DFkcSU9znl8u6LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);